# Generated by Django 3.2.9 on 2021-12-10 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=64)),
                ('apellidos', models.CharField(max_length=64)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_disparejo', models.BooleanField(default=False)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('monto_iva', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.cliente')),
            ],
            options={
                'verbose_name': 'Consumo',
                'verbose_name_plural': 'Consumos',
            },
        ),
        migrations.CreateModel(
            name='cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16)),
                ('propina', models.BooleanField(default=True)),
                ('monto_propina', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16)),
                ('estado', models.CharField(choices=[('Abierta', 'Abierta'), ('Cerrada', 'Cerrada')], default='Abierta', max_length=10)),
                ('clientes', models.ManyToManyField(blank=True, related_name='cliente_cuenta', to='engine.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
            },
        ),
        migrations.CreateModel(
            name='Cuenta_func',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_numero', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propina', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.cliente')),
                ('consumos', models.ManyToManyField(blank=True, related_name='split_consumos', to='engine.consumo')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.cuenta')),
            ],
            options={
                'verbose_name': 'Split',
                'verbose_name_plural': 'Splits',
            },
        ),
        migrations.CreateModel(
            name='local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=512, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locales',
            },
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=16)),
                ('iva', models.BooleanField(default=True)),
                ('monto_iva', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_cuenta', through='engine.consumo', to='engine.item'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='local',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='engine.local'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consumo',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.cuenta'),
        ),
        migrations.AddField(
            model_name='consumo',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.item'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='splits',
            field=models.ManyToManyField(blank=True, related_name='splits_cliente', through='engine.split', to='engine.cuenta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
