# Generated by Django 3.2.9 on 2021-12-10 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='creador',
        ),
    ]
