# Generated by Django 3.2.9 on 2021-12-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_alter_cliente_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='orden',
            name='subtotal_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16),
        ),
    ]
