# Generated by Django 3.2.9 on 2021-12-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_auto_20211207_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='propina',
        ),
        migrations.CreateModel(
            name='split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propina', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.cliente')),
                ('consumos', models.ManyToManyField(blank=True, related_name='split_consumos', to='engine.consumo')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.cuenta')),
            ],
            options={
                'verbose_name': 'Split',
                'verbose_name_plural': 'Splits',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='splits',
            field=models.ManyToManyField(blank=True, related_name='splits_cliente', through='engine.split', to='engine.cuenta'),
        ),
    ]
