# Generated by Django 3.2.9 on 2021-12-11 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_auto_20211210_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='cantidad_dividido',
            new_name='cantidad_total',
        ),
    ]
