# Generated by Django 3.2.9 on 2021-12-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_item_usuario_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
    ]
