# Generated by Django 3.2.9 on 2021-12-11 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_rename_cantidad_dividido_orden_cantidad_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='split',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='engine.split'),
        ),
    ]
