# Generated by Django 3.2.9 on 2021-12-15 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_consumo_split'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='orden',
            name='subtotal_iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
