# Generated by Django 3.2.9 on 2021-12-15 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_auto_20211214_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
