# Generated by Django 3.2.9 on 2021-12-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_alter_cuenta_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='propina',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
