# Generated by Django 4.0 on 2021-12-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0009_consumo_monto_consumo_monto_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='monto_propina',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
