# Generated by Django 4.0 on 2021-12-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0010_split_monto_propina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='total_propina',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
    ]
